login: &login2
  adapter: mysql
  database: fansof
  username: root
  password: 
  host: 127.0.0.1
  encoding: utf8
  
login: &login
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *login

production:
  <<: *login

test:
  database: db/test.sqlite3
  <<: *login